package com.jtrack.model;
// Generated 25/06/2013 8:28:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name="JOBS"
    ,schema="JTRACK"
)

public class Job  implements java.io.Serializable {


     private Long jobNo;
     private String jobName;
     private String jobDesc;
     private String jobType;
     private String jobPriority;
     private String jobStatus;
     private String jobResolution;
     private String jobStage;
     private Integer jobOrder;
     private String assignedTo;
     private String timesheetCode;
     private Double estimatedHrs;
     private Double completedHrs;
     private Date estimatedStartDate;
     private Date actualStartDate;
     private Date estimatedEndDate;
     private Date actualEndDate;
     private Long parentJobNo;
     private Boolean active;
     private Date dateCrt;
     private String userCrt;
     private Date dateMod;
     private String userMod;
     private String jobRef;
     
     private Job parentJobObj;
     private Users assignedToObj;
     private Users userCrtObj;
     private Users userModObj;

    public Job() {
    }
	
    public Job(Long jobNo) {
        this.jobNo = jobNo;
    }
   
    public Job(Long jobNo, String jobName, String jobDesc, String jobType, String jobPriority, String jobStatus, String jobResolution, String jobStage, Integer jobOrder, String assignedTo, String timesheetCode, Double estimatedHrs, Double completedHrs, Date estimatedStartDate, Date actualStartDate, Date estimatedEndDate, Date actualEndDate, Long parentJobNo, Boolean active, Date dateCrt, String userCrt, Date dateMod, String userMod, String jobRef) {
       this.jobNo = jobNo;
       this.jobName = jobName;
       this.jobDesc = jobDesc;
       this.jobType = jobType;
       this.jobPriority = jobPriority;
       this.jobStatus = jobStatus;
       this.jobResolution = jobResolution;
       this.jobStage = jobStage;
       this.jobOrder = jobOrder;
       this.assignedTo = assignedTo;
       this.timesheetCode = timesheetCode;
       this.estimatedHrs = estimatedHrs;
       this.completedHrs = completedHrs;
       this.estimatedStartDate = estimatedStartDate;
       this.actualStartDate = actualStartDate;
       this.estimatedEndDate = estimatedEndDate;
       this.actualEndDate = actualEndDate;
       this.parentJobNo = parentJobNo;
       this.active = active;
       this.dateCrt = dateCrt;
       this.userCrt = userCrt;
       this.dateMod = dateMod;
       this.userMod = userMod;
       this.jobRef = jobRef;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "JOB_NO_SEQ")
    @Column(name="JOB_NO", unique=true, nullable=false, precision=22, scale=0)
    public Long getJobNo() {
        return this.jobNo;
    }
    
    public void setJobNo(Long jobNo) {
        this.jobNo = jobNo;
    }
    
    @Column(name="JOB_NAME", length=30)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    
    @Column(name="JOB_DESC", length=4000)
    public String getJobDesc() {
        return this.jobDesc;
    }
    
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
    }
    
    @Column(name="JOB_TYPE", length=20)
    public String getJobType() {
        return this.jobType;
    }
    
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }
    
    @Column(name="JOB_PRIORITY", length=20)
    public String getJobPriority() {
        return this.jobPriority;
    }
    
    public void setJobPriority(String jobPriority) {
        this.jobPriority = jobPriority;
    }
    
    @Column(name="JOB_STATUS", length=20)
    public String getJobStatus() {
        return this.jobStatus;
    }
    
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }
    
    @Column(name="JOB_RESOLUTION", length=20)
    public String getJobResolution() {
        return this.jobResolution;
    }
    
    public void setJobResolution(String jobResolution) {
        this.jobResolution = jobResolution;
    }
    
    @Column(name="JOB_STAGE", length=20)
    public String getJobStage() {
        return this.jobStage;
    }
    
    public void setJobStage(String jobStage) {
        this.jobStage = jobStage;
    }
    
    @Column(name="JOB_ORDER", precision=22, scale=0)
    public Integer getJobOrder() {
        return this.jobOrder;
    }
    
    public void setJobOrder(Integer jobOrder) {
        this.jobOrder = jobOrder;
    }
    
    @Column(name="ASSIGNED_TO", length=20)
    public String getAssignedTo() {
        return this.assignedTo;
    }
    
    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }
    
    @Column(name="TIMESHEET_CODE", length=20)
    public String getTimesheetCode() {
        return this.timesheetCode;
    }
    
    public void setTimesheetCode(String timesheetCode) {
        this.timesheetCode = timesheetCode;
    }
    
    @Column(name="ESTIMATED_HRS", precision=22, scale=0)
    public Double getEstimatedHrs() {
        return this.estimatedHrs;
    }
    
    public void setEstimatedHrs(Double estimatedHrs) {
        this.estimatedHrs = estimatedHrs;
    }
    
    @Column(name="COMPLETED_HRS", precision=22, scale=0)
    public Double getCompletedHrs() {
        return this.completedHrs;
    }
    
    public void setCompletedHrs(Double completedHrs) {
        this.completedHrs = completedHrs;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ESTIMATED_START_DATE")
    public Date getEstimatedStartDate() {
        return this.estimatedStartDate;
    }
    
    public void setEstimatedStartDate(Date estimatedStartDate) {
        this.estimatedStartDate = estimatedStartDate;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_START_DATE")
    public Date getActualStartDate() {
        return this.actualStartDate;
    }
    
    public void setActualStartDate(Date actualStartDate) {
        this.actualStartDate = actualStartDate;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ESTIMATED_END_DATE")
    public Date getEstimatedEndDate() {
        return this.estimatedEndDate;
    }
    
    public void setEstimatedEndDate(Date estimatedEndDate) {
        this.estimatedEndDate = estimatedEndDate;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_END_DATE")
    public Date getActualEndDate() {
        return this.actualEndDate;
    }
    
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }
    
    @Column(name="PARENT_JOB_NO", precision=22, scale=0)
    public Long getParentJobNo() {
        return this.parentJobNo;
    }
    
    public void setParentJobNo(Long parentJobNo) {
        this.parentJobNo = parentJobNo;
    }
    
    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CRT")
    public Date getDateCrt() {
        return this.dateCrt;
    }
    
    public void setDateCrt(Date dateCrt) {
        this.dateCrt = dateCrt;
    }
    
    @Column(name="USER_CRT", length=20)
    public String getUserCrt() {
        return this.userCrt;
    }
    
    public void setUserCrt(String userCrt) {
        this.userCrt = userCrt;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_MOD")
    public Date getDateMod() {
        return this.dateMod;
    }
    
    public void setDateMod(Date dateMod) {
        this.dateMod = dateMod;
    }
    
    @Column(name="USER_MOD", length=20)
    public String getUserMod() {
        return this.userMod;
    }
    
    public void setUserMod(String userMod) {
        this.userMod = userMod;
    }
    
    @Column(name="JOB_REF", length=100)
    public String getJobRef() {
        return this.jobRef;
    }
    
    public void setJobRef(String jobRef) {
        this.jobRef = jobRef;
    }

    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "PARENT_JOB_NO", referencedColumnName = "JOB_NO", insertable = false, updatable = false)
    public Job getParentJobObj() {
        return parentJobObj;
    }

    public void setParentJobObj(Job parentJobObj) {
        this.parentJobObj = parentJobObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "ASSIGNED_TO", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getAssignedToObj() {
        return assignedToObj;
    }

    public void setAssignedToObj(Users assignedToObj) {
        this.assignedToObj = assignedToObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "USER_CRT", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getUserCrtObj() {
        return userCrtObj;
    }

    public void setUserCrtObj(Users userCrtObj) {
        this.userCrtObj = userCrtObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "USER_MOD", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getUserModObj() {
        return userModObj;
    }

    public void setUserModObj(Users userModObj) {
        this.userModObj = userModObj;
    }
}


