package com.jtrack.model;
// Generated 25/06/2013 8:28:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Timesheet generated by hbm2java
 */
@Entity
@Table(name="TIMESHEET"
    ,schema="JTRACK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"USER_ID", "JOB_NO", "WORKED_DATE"}) 
)
public class Timesheet  implements java.io.Serializable {


     private String timesheetId;
     private String userId;
     private Long jobNo;
     private Date workedDate;
     private double workedHrs;
     private String timesheetCode;
     private Boolean active;
     private Date dateCrt;
     private String userCrt;
     private Date dateMod;
     private String userMod;
     
     private Job jobObj;
     private Users userObj;
     private Users userCrtObj;
     private Users userModObj;

    public Timesheet() {
    }

    public Timesheet(String timesheetId) {
        this.timesheetId = timesheetId;
    }
   
    public Timesheet(String timesheetId, String userId, Long jobNo, Date workedDate, double workedHrs, String timesheetCode, Boolean active, Date dateCrt, String userCrt, Date dateMod, String userMod) {
       this.timesheetId = timesheetId;
       this.userId = userId;
       this.jobNo = jobNo;
       this.workedDate = workedDate;
       this.workedHrs = workedHrs;
       this.timesheetCode = timesheetCode;
       this.active = active;
       this.dateCrt = dateCrt;
       this.userCrt = userCrt;
       this.dateMod = dateMod;
       this.userMod = userMod;
    }
   
    @Id 
    @Column(name="TIMESHEET_ID", unique=true, nullable=false, length=100)
    public String getTimesheetId() {
        return this.timesheetId;
    }
    
    public void setTimesheetId(String timesheetId) {
        this.timesheetId = timesheetId;
    }
    
    @Column(name="USER_ID", length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="JOB_NO")
    public Long getJobNo() {
        return this.jobNo;
    }
    
    public void setJobNo(Long jobNo) {
        this.jobNo = jobNo;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="WORKED_DATE", length=7)
    public Date getWorkedDate() {
        return this.workedDate;
    }
    
    public void setWorkedDate(Date workedDate) {
        this.workedDate = workedDate;
    }
    
    @Column(name="WORKED_HRS", precision=22, scale=0)
    public double getWorkedHrs() {
        return this.workedHrs;
    }
    
    public void setWorkedHrs(double workedHrs) {
        this.workedHrs = workedHrs;
    }
    
    @Column(name="TIMESHEET_CODE", length=250)
    public String getTimesheetCode() {
        return this.timesheetCode;
    }
    
    public void setTimesheetCode(String timesheetCode) {
        this.timesheetCode = timesheetCode;
    }
    
    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CRT")
    public Date getDateCrt() {
        return this.dateCrt;
    }
    
    public void setDateCrt(Date dateCrt) {
        this.dateCrt = dateCrt;
    }
    
    @Column(name="USER_CRT", length=20)
    public String getUserCrt() {
        return this.userCrt;
    }
    
    public void setUserCrt(String userCrt) {
        this.userCrt = userCrt;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_MOD")
    public Date getDateMod() {
        return this.dateMod;
    }
    
    public void setDateMod(Date dateMod) {
        this.dateMod = dateMod;
    }
    
    @Column(name="USER_MOD", length=20)
    public String getUserMod() {
        return this.userMod;
    }
    
    public void setUserMod(String userMod) {
        this.userMod = userMod;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "JOB_NO", referencedColumnName = "JOB_NO", insertable = false, updatable = false)
    public Job getJobObj() {
        return jobObj;
    }

    public void setJobObj(Job jobObj) {
        this.jobObj = jobObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "USER_ID", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getUserObj() {
        return userObj;
    }

    public void setUserObj(Users userObj) {
        this.userObj = userObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "USER_CRT", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getUserCrtObj() {
        return userCrtObj;
    }

    public void setUserCrtObj(Users userCrtObj) {
        this.userCrtObj = userCrtObj;
    }
    
    @ManyToOne(fetch=FetchType.EAGER, optional=true)
    @JoinColumn(name = "USER_MOD", referencedColumnName = "USER_ID", insertable = false, updatable = false)
    public Users getUserModObj() {
        return userModObj;
    }

    public void setUserModObj(Users userModObj) {
        this.userModObj = userModObj;
    }
}


